### PR TITLE
Add mautic

### PR DESCRIPTION
**Pull request by MagsMagnoli**
Added mautic tracking. This only works in production
Added mautic volunteer form

### CODE REVIEW

**Comment by Quinncuatro** [comment]
What is this actually doing? When I looked last night there didn't seem to be any change on the preview link.

**Comment by Quinncuatro** [comment]
Any way we can add an actual form to a /volunteer page or something before we fold this in?

**Comment by Quinncuatro** [comment]
I think that's a smart way to handle it. Keep it on /volunteer and we can point the link in the footer to it. But it should definitely be part of the email drip for newsletter subscribers. 

"Thanks for signing up for the newsletters. We promise not to spam you too often. Also here's a link to our volunteer form if you want to get involved with the movement."

**Comment by feralislatr** [comment]
I'll play with some styling here later on. 

I think the volunteer form is a few pages so idk if we want to hold up this pr with that

**Comment by Quinncuatro** [comment]
Agreed. Let's get the styling for this done, ship it, and open a new PR for the volunteer form.

**Comment by feralislatr** [comment]
updated the styles @MagsMagnoli @Quinncuatro

**Comment by Quinncuatro** [comment]
Everything looks great!

Being super nitpicky, though. We should put a little bit of language in there for what signing up is, like "we'd love it if you signed up for our newsletter so that you can get all the latest news on actionable dates throughout the year" rather than an unexplained "Sign Up" button.

**Comment by feralislatr** [comment]
updated the styles @MagsMagnoli @

> Everything looks great!
> 
> Being super nitpicky, though. We should put a little bit of language in there for what signing up is, like "we'd love it if you signed up for our newsletter so that you can get all the latest news on actionable dates throughout the year" rather than an unexplained "Sign Up" button.

yea I had asked for language, didn't really get anything concrete. I figured once people saw it, they'd figure something out.

**Comment by Quinncuatro** [comment]
Continued excellent work, @feralislatr!

**Comment by Quinncuatro** [comment]
Two final things:

A) Can someone confirm that my "Chester Tester" submission made it into Mautic? Once this is good I'll merge it. 

B) Probably a separate PR but can we redirect a successful form submission to a page on the site rather than black text on a white background?

**Comment by MagsMagnoli** [comment]
@Quinncuatro your submission was received

**Comment by feralislatr** [comment]
the mautic confirmation message has been updated

**Pull request merged**
