### PR TITLE
update page hierarchy and style

### PR DESCRIPTION
**Pull request by feralislatr**
- switch section headings to use h2 instead of h1
- use LietzLindauHamburg font in h2 instead of Alpenkreuzer
- add brand style colors
- add logo to header
- remove logo from footer
- update scoping of css modules
- add open sans as body text
- refactor navbar
    - remove hamburger
- change seo title from "More Info Coming Soon" to "May Day Strike"

### CODE REVIEW

**Comment by feralislatr** [comment]
need to incorporate the rest of the brand guide changes here

**Comment by feralislatr** [comment]
made a few changes to the landing page style. lmk what you think

**Comment by Quinncuatro** [comment]
Could you address the changes this all made to the FAQ and Links pages? 

Need a little distance between the header and the H1/2 text right underneath it. 

And your CSS changes gunked up the body text sizes of the FAQ. 

Otherwise, looks incredible. Great changes!

**Comment by Quinncuatro** [comment]
@feralislatr ^^

**Comment by feralislatr** [comment]
> Could you address the changes this all made to the FAQ and Links pages?
> 
> Need a little distance between the header and the H1/2 text right underneath it.
> 
> And your CSS changes gunked up the body text sizes of the FAQ.
> 
> Otherwise, looks incredible. Great changes!

my b, forgot to look at those. that's what I get for doing stuff late. I'll check it out tomorrow

**Comment by feralislatr** [comment]
> Could you address the changes this all made to the FAQ and Links pages?
> 
> Need a little distance between the header and the H1/2 text right underneath it.
> 
> And your CSS changes gunked up the body text sizes of the FAQ.
> 
> Otherwise, looks incredible. Great changes!

the other pages should be fixed now

**Comment by Quinncuatro** [comment]
Looks a lot better!

Just one more thing I'd fix before we merge this in: the menu bar is wonky on a fresh page load. 

image

**Comment by Quinncuatro** [comment]
Looks good to me! Gonna merge this in and open up an issue about the strange menubar behavior.

**Pull request merged**
